version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tap
    versions:
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
